name: Build Check 

on:
    push:
        branches-ignore:
            - main

jobs:
    Build-Check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Bun
              run: curl -fsSL https://bun.sh/install | bash

            - name: Add Bun to PATH
              run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

            - name: Install Dependencies
              run: bun install

            - name: Build Project
              run: bun run build
              